
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-11T12:23:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc1ef29cf38ee48d24b87805cf3cd8b4e32d9a3d",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
