from djing.core.application import Application as Application
from typing import Callable, Literal

def get_application() -> Application: ...
def access_required(func: Callable | None = None, *, allowed_user_type: Literal['guest', 'authenticated'] = 'guest'): ...
