# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from apifff.api_client import ApiClient


class MatchEntityApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_clubs_equipes_matchs_get_subresource_club_subresource(self, cl_no, equipes, **kwargs):  # noqa: E501
        """Retrieves a Club resource.  # noqa: E501

        Retrieves a Club resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_clubs_equipes_matchs_get_subresource_club_subresource(cl_no, equipes, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cl_no: Club identifier (required)
        :param str equipes: Equipe identifier (required)
        :param int page: The collection page number
        :param int cl_no:
        :param int competition_cp_no:
        :param list[int] competition_cp_no:
        :param str ma_dat_before:
        :param str ma_dat_strictly_before:
        :param str ma_dat_after:
        :param str ma_dat_strictly_after:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.api_clubs_equipes_matchs_get_subresource_club_subresource_with_http_info(cl_no, equipes,
                                                                                                 **kwargs)  # noqa: E501
        else:
            (data) = self.api_clubs_equipes_matchs_get_subresource_club_subresource_with_http_info(cl_no, equipes,
                                                                                                   **kwargs)  # noqa: E501
            return data

    def api_clubs_equipes_matchs_get_subresource_club_subresource_with_http_info(self, cl_no, equipes,
                                                                                 **kwargs):  # noqa: E501
        """Retrieves a Club resource.  # noqa: E501

        Retrieves a Club resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.api_clubs_equipes_matchs_get_subresource_club_subresource_with_http_info(cl_no, equipes, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cl_no: Club identifier (required)
        :param str equipes: Equipe identifier (required)
        :param int page: The collection page number
        :param int cl_no:
        :param int competition_cp_no:
        :param list[int] competition_cp_no:
        :param str ma_dat_before:
        :param str ma_dat_strictly_before:
        :param str ma_dat_after:
        :param str ma_dat_strictly_after:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cl_no', 'equipes', 'page', 'cl_no', 'competition_cp_no', 'competition_cp_no', 'ma_dat_before',
                      'ma_dat_strictly_before', 'ma_dat_after', 'ma_dat_strictly_after']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_clubs_equipes_matchs_get_subresource_club_subresource" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cl_no' is set
        if ('cl_no' not in params or
                params['cl_no'] is None):
            raise ValueError(
                "Missing the required parameter `cl_no` when calling `api_clubs_equipes_matchs_get_subresource_club_subresource`")  # noqa: E501
        # verify the required parameter 'equipes' is set
        if ('equipes' not in params or
                params['equipes'] is None):
            raise ValueError(
                "Missing the required parameter `equipes` when calling `api_clubs_equipes_matchs_get_subresource_club_subresource`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cl_no' in params:
            path_params['clNo'] = params['cl_no']  # noqa: E501
        if 'equipes' in params:
            path_params['equipes'] = params['equipes']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'cl_no' in params:
            query_params.append(('clNo', params['cl_no']))  # noqa: E501
        if 'competition_cp_no' in params:
            query_params.append(('competition.cp_no', params['competition_cp_no']))  # noqa: E501
        if 'competition_cp_no' in params:
            query_params.append(('competition.cp_no[]', params['competition_cp_no']))  # noqa: E501
            collection_formats['competition.cp_no[]'] = 'multi'  # noqa: E501
        if 'ma_dat_before' in params:
            query_params.append(('ma_dat[before]', params['ma_dat_before']))  # noqa: E501
        if 'ma_dat_strictly_before' in params:
            query_params.append(('ma_dat[strictly_before]', params['ma_dat_strictly_before']))  # noqa: E501
        if 'ma_dat_after' in params:
            query_params.append(('ma_dat[after]', params['ma_dat_after']))  # noqa: E501
        if 'ma_dat_strictly_after' in params:
            query_params.append(('ma_dat[strictly_after]', params['ma_dat_strictly_after']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/clubs/{clNo}/equipes/{equipes}/matchs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2007',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_calendrier_of_club_match_entity_collection(self, cl_no, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchEntity resources.  # noqa: E501

        Retrieves the collection of MatchEntity resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_calendrier_of_club_match_entity_collection(, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param  : (required)
        :param int page: The collection page number
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_calendrier_of_club_match_entity_collection_with_http_info(cl_no, **kwargs)  # noqa: E501
        else:
            (data) = self.get_calendrier_of_club_match_entity_collection_with_http_info(cl_no, **kwargs)  # noqa: E501
            return data

    def get_calendrier_of_club_match_entity_collection_with_http_info(self, cl_no, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchEntity resources.  # noqa: E501

        Retrieves the collection of MatchEntity resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_calendrier_of_club_match_entity_collection_with_http_info(, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param  : (required)
        :param int page: The collection page number
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['', 'page']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_calendrier_of_club_match_entity_collection" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter '' is set
        if ('' not in params or
                params[''] is None):
            raise ValueError(
                "Missing the required parameter `` when calling `get_calendrier_of_club_match_entity_collection`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if '' in params:
            path_params['clNo'] = params['']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/clubs/{clNo}/calendrier', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2007',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_match_entity_collection(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchEntity resources.  # noqa: E501

        Permet de récupérer les matchs, /!\\ toujours passer des dates en filtre sinon timeout !!!  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_entity_collection(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The collection page number
        :param int cl_no:
        :param int competition_cp_no:
        :param list[int] competition_cp_no:
        :param str ma_dat_before:
        :param str ma_dat_strictly_before:
        :param str ma_dat_after:
        :param str ma_dat_strictly_after:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_match_entity_collection_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_match_entity_collection_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_match_entity_collection_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchEntity resources.  # noqa: E501

        Permet de récupérer les matchs, /!\\ toujours passer des dates en filtre sinon timeout !!!  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_entity_collection_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The collection page number
        :param int cl_no:
        :param int competition_cp_no:
        :param list[int] competition_cp_no:
        :param str ma_dat_before:
        :param str ma_dat_strictly_before:
        :param str ma_dat_after:
        :param str ma_dat_strictly_after:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'cl_no', 'competition_cp_no', 'competition_cp_no', 'ma_dat_before',
                      'ma_dat_strictly_before', 'ma_dat_after', 'ma_dat_strictly_after']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_match_entity_collection" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'cl_no' in params:
            query_params.append(('clNo', params['cl_no']))  # noqa: E501
        if 'competition_cp_no' in params:
            query_params.append(('competition.cp_no', params['competition_cp_no']))  # noqa: E501
        if 'competition_cp_no' in params:
            query_params.append(('competition.cp_no[]', params['competition_cp_no']))  # noqa: E501
            collection_formats['competition.cp_no[]'] = 'multi'  # noqa: E501
        if 'ma_dat_before' in params:
            query_params.append(('ma_dat[before]', params['ma_dat_before']))  # noqa: E501
        if 'ma_dat_strictly_before' in params:
            query_params.append(('ma_dat[strictly_before]', params['ma_dat_strictly_before']))  # noqa: E501
        if 'ma_dat_after' in params:
            query_params.append(('ma_dat[after]', params['ma_dat_after']))  # noqa: E501
        if 'ma_dat_strictly_after' in params:
            query_params.append(('ma_dat[strictly_after]', params['ma_dat_strictly_after']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/match_entities', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2007',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_match_entity_item(self, ma_no, **kwargs):  # noqa: E501
        """Retrieves a MatchEntity resource.  # noqa: E501

        Retrieves a MatchEntity resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_entity_item(ma_no, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ma_no: Resource identifier (required)
        :return: MatchEntityJsonldMatch
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_match_entity_item_with_http_info(ma_no, **kwargs)  # noqa: E501
        else:
            (data) = self.get_match_entity_item_with_http_info(ma_no, **kwargs)  # noqa: E501
            return data

    def get_match_entity_item_with_http_info(self, ma_no, **kwargs):  # noqa: E501
        """Retrieves a MatchEntity resource.  # noqa: E501

        Retrieves a MatchEntity resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_entity_item_with_http_info(ma_no, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str ma_no: Resource identifier (required)
        :return: MatchEntityJsonldMatch
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ma_no']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_match_entity_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ma_no' is set
        if ('ma_no' not in params or
                params['ma_no'] is None):
            raise ValueError(
                "Missing the required parameter `ma_no` when calling `get_match_entity_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'ma_no' in params:
            path_params['maNo'] = params['ma_no']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/match_entities/{maNo}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MatchEntityJsonldMatch',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
