from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest

web: Incomplete

def login(request: HttpRequest): ...
def index(request: HttpRequest): ...
def dashboard(request: HttpRequest, dashboard_name: str): ...
def read_item(request, item_id: int): ...
