from .Allinone import *
from .module.book import *
from .module.calculator import *
from .module.erfenchazhao_py import *
from .module.math_cal_py import *
from .module.student_py import *
from .module.tuxing_cal import *
from .module.xiaogongju import *
from lotterytickets import *
from numberandchinese import *