from _typeshed import Incomplete

class InertiaApplication:
    middlewares: Incomplete
    settings: Incomplete
    booted: bool
    package_path: Incomplete
    dev_mode: Incomplete
    def __init__(self) -> None: ...
    def boot(self) -> None: ...
    def get_dev_mode(self) -> bool: ...
    def get_djing_settings(self, django_settings, inertia_settings): ...
    def get_merged_settings(self, django_settings, djing_settings): ...
    def get_template_dirs(self) -> list: ...
    def get_static_dirs(self) -> list: ...
