from _typeshed import Incomplete as Incomplete

def propagate(formula, assumptions) -> None: ...

class PreProcessor:
    formula: Incomplete
    steps: Incomplete
    def __init__(self, formula) -> None: ...
    def add_call(self, fn, args, kwargs) -> None: ...
    @staticmethod
    def call_step(step, formula) -> None: ...
    def propagate(self, assumptions) -> None: ...
    def process(self) -> None: ...
