# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .didcomm_message_show import DidcommMessageShow
from .resource import Resource


class DidcommMessageResource(Resource):
    """
    The didcomm-message's resource (with general for all resources' fields).
    """

    data: DidcommMessageShow

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
