# This file was auto-generated by Fern from our API Definition.

import typing

from .ecdsa_secp_256_k_1_verification_key_2019 import EcdsaSecp256K1VerificationKey2019
from .verification_method_multikey import VerificationMethodMultikey

VerificationMethod = typing.Union[VerificationMethodMultikey, EcdsaSecp256K1VerificationKey2019]
