
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-18T10:56:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ed1d429cbd7c4f21d779c7e4ac65ddc90512b80",
 "version": "2.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
