from __future__ import annotations
from typing import Type, Union, Optional, BinaryIO, Tuple
import os

version: str = ...

version_info: Tuple[int, int, int] = ...

LUNASVG_VERSION: int = ...
LUNASVG_VERSION_MAJOR: int = ...
LUNASVG_VERSION_MICRO: int = ...
LUNASVG_VERSION_MINOR: int = ...
LUNASVG_VERSION_STRING: str = ...
