from _typeshed import Incomplete as Incomplete
from argparse import ArgumentParser
from optilog.blackbox import SystemBlackBox as SystemBlackBox
from optilog.tuning.configurators.abstract_configurator import AbstractConfigurator as AbstractConfigurator

def matching_output(content: str, reg: str): ...
def set_wrapper_subparser(configurator: AbstractConfigurator, parent: ArgumentParser): ...

class ConfiguratorWrapper:
    configurator: Incomplete
    args: Incomplete
    params: Incomplete
    def __init__(self, configurator: AbstractConfigurator, args, params) -> None: ...
    def get_blackbox(self) -> None: ...
    def main(self) -> None: ...
    def report_error(self, bb) -> None: ...
    def report_result(self, bb: SystemBlackBox): ...

def configurator_wrapper_main(configurator: AbstractConfigurator, args, params): ...
