# This file was auto-generated by Fern from our API Definition.

import typing

from .file_extension import FileExtension
from .file_format import FileFormat

ListRequestFileFormatItem = typing.Union[FileFormat, FileExtension]
