bigquery_resource="""
protoPayload.@type
protoPayload.authenticationInfo.principalEmail
protoPayload.requestMetadata.callerIp
protoPayload.requestMetadata.callerSuppliedUserAgent
protoPayload.serviceName
protoPayload.methodName
protoPayload.authorizationInfo.resource
protoPayload.authorizationInfo.permission
protoPayload.authorizationInfo.granted
protoPayload.resourceName
protoPayload.serviceData.@type
protoPayload.serviceData.jobInsertRequest.resource.jobName.projectId
protoPayload.serviceData.jobInsertRequest.resource.jobConfiguration.query.query
protoPayload.serviceData.jobInsertRequest.resource.jobConfiguration.query.createDisposition
protoPayload.serviceData.jobInsertRequest.resource.jobConfiguration.query.writeDisposition
protoPayload.serviceData.jobInsertRequest.resource.jobConfiguration.query.queryPriority
protoPayload.serviceData.jobInsertRequest.resource.jobConfiguration.dryRun
protoPayload.serviceData.jobInsertResponse.resource.jobName.projectId
protoPayload.serviceData.jobInsertResponse.resource.jobName.location
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.query
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.destinationTable.projectId
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.destinationTable.datasetId
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.destinationTable.tableId
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.createDisposition
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.writeDisposition
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.queryPriority
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.query.statementType
protoPayload.serviceData.jobInsertResponse.resource.jobConfiguration.dryRun
protoPayload.serviceData.jobInsertResponse.resource.jobStatus.state
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.createTime
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedTables.projectId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedTables.datasetId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedTables.tableId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.totalTablesProcessed
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedViews.projectId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedViews.datasetId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.referencedViews.tableId
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.totalViewsProcessed
protoPayload.serviceData.jobInsertResponse.resource.jobStatistics.reservation
insertId
resource.type
resource.labels.project_id
timestamp
severity
logName
receiveTimestamp
"""
bigquery_table="""
protoPayload.@type
protoPayload.authenticationInfo.principalEmail
protoPayload.authenticationInfo.serviceAccountDelegationInfo.firstPartyPrincipal.principalEmail
protoPayload.serviceName
protoPayload.methodName
protoPayload.authorizationInfo.resource
protoPayload.authorizationInfo.permission
protoPayload.authorizationInfo.granted
protoPayload.resourceName
protoPayload.metadata.@type
protoPayload.metadata.tableDataRead.rowCount
protoPayload.metadata.tableDataRead.reason
protoPayload.metadata.tableDataRead.readStream
insertId
resource.type
resource.labels.dataset_id
resource.labels.table_id
resource.labels.project_id
timestamp
severity
logName
operation.id
operation.producer
operation.last
receiveTimestamp"""
bigquery_dataset="""
protoPayload.@type
protoPayload.authenticationInfo.principalEmail
protoPayload.requestMetadata.callerIp
protoPayload.requestMetadata.callerSuppliedUserAgent
protoPayload.serviceName
protoPayload.methodName
protoPayload.authorizationInfo.resource
protoPayload.authorizationInfo.permission
protoPayload.authorizationInfo.granted
protoPayload.resourceName
protoPayload.metadata.@type
protoPayload.metadata.tableDataRead.jobName
protoPayload.metadata.tableDataRead.reason
insertId
resource.type
resource.labels.dataset_id
resource.labels.project_id
timestamp
severity
logName
receiveTimestamp
"""
bigquery_project="""
protoPayload.@type
protoPayload.authenticationInfo.principalEmail
protoPayload.requestMetadata.callerIp
protoPayload.requestMetadata.callerSuppliedUserAgent
protoPayload.serviceName
protoPayload.methodName
protoPayload.authorizationInfo.resource
protoPayload.authorizationInfo.permission
protoPayload.authorizationInfo.granted
protoPayload.resourceName
protoPayload.metadata.@type
protoPayload.metadata.jobChange.job.jobStats.queryStats.billingTier
protoPayload.metadata.jobChange.job.jobStats.queryStats.totalProcessedBytes
protoPayload.metadata.jobChange.job.jobStats.queryStats.totalBilledBytes
protoPayload.metadata.jobChange.job.jobStats.totalSlotMs
protoPayload.metadata.jobChange.job.jobStats.endTime
protoPayload.metadata.jobChange.job.jobStats.reservation
protoPayload.metadata.jobChange.job.jobStats.startTime
protoPayload.metadata.jobChange.job.jobStats.createTime
protoPayload.metadata.jobChange.job.jobName
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.query
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.createDisposition
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.destinationTable
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.statementType
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.writeDisposition
protoPayload.metadata.jobChange.job.jobConfig.queryConfig.priority
protoPayload.metadata.jobChange.job.jobConfig.type
protoPayload.metadata.jobChange.job.jobStatus.jobState
protoPayload.metadata.jobChange.after
insertId
resource.type
resource.labels.project_id
resource.labels.location
timestamp
severity
logName
operation.id
operation.producer
operation.last
receiveTimestamp
"""