# This file was auto-generated by Fern from our API Definition.

import typing

ImageToImageModels = typing.Union[
    typing.Literal[
        "dream_shaper",
        "dreamlike_2",
        "sd_2",
        "sd_1_5",
        "dall_e",
        "instruct_pix2pix",
        "openjourney_2",
        "openjourney",
        "analog_diffusion",
        "protogen_5_3",
        "jack_qiao",
        "rodent_diffusion_1_5",
    ],
    typing.Any,
]
