
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-17T13:17:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9aee259755b08fbb63aa4a96a1be666c97f3d4f6",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
