# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PouleJsonldPhase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'OneOfPouleJsonldPhaseContext',
        'id': 'str',
        'type': 'str',
        'stage_number': 'int'
    }

    attribute_map = {
        'context': '@context',
        'id': '@id',
        'type': '@type',
        'stage_number': 'stage_number'
    }

    def __init__(self, context=None, id=None, type=None, stage_number=None):  # noqa: E501
        """PouleJsonldPhase - a model defined in Swagger"""  # noqa: E501
        self._context = None
        self._id = None
        self._type = None
        self._stage_number = None
        self.discriminator = None
        if context is not None:
            self.context = context
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if stage_number is not None:
            self.stage_number = stage_number

    @property
    def context(self):
        """Gets the context of this PouleJsonldPhase.  # noqa: E501


        :return: The context of this PouleJsonldPhase.  # noqa: E501
        :rtype: OneOfPouleJsonldPhaseContext
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this PouleJsonldPhase.


        :param context: The context of this PouleJsonldPhase.  # noqa: E501
        :type: OneOfPouleJsonldPhaseContext
        """

        self._context = context

    @property
    def id(self):
        """Gets the id of this PouleJsonldPhase.  # noqa: E501


        :return: The id of this PouleJsonldPhase.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PouleJsonldPhase.


        :param id: The id of this PouleJsonldPhase.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this PouleJsonldPhase.  # noqa: E501


        :return: The type of this PouleJsonldPhase.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PouleJsonldPhase.


        :param type: The type of this PouleJsonldPhase.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def stage_number(self):
        """Gets the stage_number of this PouleJsonldPhase.  # noqa: E501


        :return: The stage_number of this PouleJsonldPhase.  # noqa: E501
        :rtype: int
        """
        return self._stage_number

    @stage_number.setter
    def stage_number(self, stage_number):
        """Sets the stage_number of this PouleJsonldPhase.


        :param stage_number: The stage_number of this PouleJsonldPhase.  # noqa: E501
        :type: int
        """

        self._stage_number = stage_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PouleJsonldPhase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PouleJsonldPhase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
