# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.models.any_of_calcul_serie_cours_calcul_serie_cours_match4 import AnyOfCalculSerieCoursCalculSerieCoursMatch4  # noqa: E501
from apifff.rest import ApiException


class TestAnyOfCalculSerieCoursCalculSerieCoursMatch4(unittest.TestCase):
    """AnyOfCalculSerieCoursCalculSerieCoursMatch4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfCalculSerieCoursCalculSerieCoursMatch4(self):
        """Test AnyOfCalculSerieCoursCalculSerieCoursMatch4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apifff.models.any_of_calcul_serie_cours_calcul_serie_cours_match4.AnyOfCalculSerieCoursCalculSerieCoursMatch4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
