# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from apifff.api_client import ApiClient


class MatchFeuilleApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_match_feuille_collection(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchFeuille resources.  # noqa: E501

        Retrieves the collection of MatchFeuille resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_feuille_collection(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int match_entity_ma_no:
        :param list[int] match_entity_ma_no:
        :return: InlineResponse20016
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_match_feuille_collection_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_match_feuille_collection_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_match_feuille_collection_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchFeuille resources.  # noqa: E501

        Retrieves the collection of MatchFeuille resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_feuille_collection_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int match_entity_ma_no:
        :param list[int] match_entity_ma_no:
        :return: InlineResponse20016
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['match_entity_ma_no', 'match_entity_ma_no']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_match_feuille_collection" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'match_entity_ma_no' in params:
            query_params.append(('match_entity.ma_no', params['match_entity_ma_no']))  # noqa: E501
        if 'match_entity_ma_no' in params:
            query_params.append(('match_entity.ma_no[]', params['match_entity_ma_no']))  # noqa: E501
            collection_formats['match_entity.ma_no[]'] = 'multi'  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/match_feuilles', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20016',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_match_feuille_item(self, cfm_no, **kwargs):  # noqa: E501
        """Retrieves a MatchFeuille resource.  # noqa: E501

        Retrieves a MatchFeuille resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_feuille_item(cfm_no, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cfm_no: Resource identifier (required)
        :return: MatchFeuilleJsonldMatchFeuille
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_match_feuille_item_with_http_info(cfm_no, **kwargs)  # noqa: E501
        else:
            (data) = self.get_match_feuille_item_with_http_info(cfm_no, **kwargs)  # noqa: E501
            return data

    def get_match_feuille_item_with_http_info(self, cfm_no, **kwargs):  # noqa: E501
        """Retrieves a MatchFeuille resource.  # noqa: E501

        Retrieves a MatchFeuille resource.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_feuille_item_with_http_info(cfm_no, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cfm_no: Resource identifier (required)
        :return: MatchFeuilleJsonldMatchFeuille
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cfm_no']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_match_feuille_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cfm_no' is set
        if ('cfm_no' not in params or
                params['cfm_no'] is None):
            raise ValueError("Missing the required parameter `cfm_no` when calling `get_match_feuille_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cfm_no' in params:
            path_params['cfmNo'] = params['cfm_no']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/match_feuilles/{cfmNo}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MatchFeuilleJsonldMatchFeuille',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
