"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from panora_sdk.types import BaseModel
from panora_sdk.utils import FieldMetadata, PathParamMetadata
from typing import TypedDict
from typing_extensions import Annotated


class PathParamVertical(str, Enum):
    TICKETING = "ticketing"
    MARKETINGAUTOMATION = "marketingautomation"
    CRM = "crm"
    FILESTORAGE = "filestorage"
    ATS = "ats"
    HRIS = "hris"
    ACCOUNTING = "accounting"
    ECOMMERCE = "ecommerce"

class StatusRequestTypedDict(TypedDict):
    vertical: PathParamVertical
    

class StatusRequest(BaseModel):
    vertical: Annotated[PathParamVertical, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    
