"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, TypedDict


class CreateBatchLinkedUserDtoTypedDict(TypedDict):
    linked_user_origin_ids: Nullable[List[str]]
    r"""The ids of the users in the context of your own software"""
    alias: Nullable[str]
    r"""Your company alias"""
    

class CreateBatchLinkedUserDto(BaseModel):
    linked_user_origin_ids: Nullable[List[str]]
    r"""The ids of the users in the context of your own software"""
    alias: Nullable[str]
    r"""Your company alias"""
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["linked_user_origin_ids", "alias"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        
