"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class LoginDtoTypedDict(TypedDict):
    email: str
    password_hash: str
    id_user: NotRequired[str]
    

class LoginDto(BaseModel):
    email: str
    password_hash: str
    id_user: Optional[str] = None
    
