"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import TypedDict


class UpdatePullFrequencyResponseBodyTypedDict(TypedDict):
    pass
    

class UpdatePullFrequencyResponseBody(BaseModel):
    pass
    
