# generated by datamodel-codegen:
#   filename:  api_token_scopes.json
#   timestamp: 2024-09-02T14:02:23+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import Field

from . import CanvasBaseModel



class Scope(CanvasBaseModel):
    resource: Optional[str] = Field(None, examples=['courses'])
    """
    The resource the scope is associated with
    """

    resource_name: Optional[str] = Field(None, examples=['Courses'], repr=False)
    """
    The localized resource name
    """

    controller: Optional[str] = Field(None, examples=['courses'], repr=False)
    """
    The controller the scope is associated to
    """

    action: Optional[str] = Field(None, examples=['index'], repr=False)
    """
    The controller action the scope is associated to
    """

    verb: Optional[str] = Field(None, examples=['GET'], repr=False)
    """
    The HTTP verb for the scope
    """

    scope: Optional[str] = Field(None, examples=['url:GET|/api/v1/courses'], repr=False)
    """
    The identifier for the scope
    """

