# generated by datamodel-codegen:
#   filename:  tabs.json
#   timestamp: 2024-09-02T14:02:23+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import Field

from . import CanvasBaseModel



class Tab(CanvasBaseModel):
    html_url: Optional[str] = Field(
        None, examples=['/courses/1/external_tools/4'], repr=False
    )
    id: Optional[str] = Field(None, examples=['context_external_tool_4'])
    label: Optional[str] = Field(None, examples=['WordPress'])
    type: Optional[str] = Field(None, examples=['external'], repr=False)
    hidden: Optional[bool] = Field(None, examples=[True], repr=False)
    """
    only included if true
    """

    visibility: Optional[str] = Field(None, examples=['public'], repr=False)
    """
    possible values are: public, members, admins, and none
    """

    position: Optional[int] = Field(None, examples=[2], repr=False)
    """
    1 based
    """

