
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-16T17:57:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0136024dc70e0a6fb973aa31d7883d5b2e95d07a",
 "version": "1.8.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
