from .初始化_普通模式 import 初始化_普通模式
from .初始化_禁用图片 import 初始化_禁用图片
from .取当前页面网址 import 取当前页面网址
from .取网页源码 import 取网页源码
from .截图并保存 import 截图并保存
from .等待元素出现 import 等待元素出现
from .等待元素可点击 import 等待元素可点击
from .等待元素可见 import 等待元素可见
from .获取Cookies import 获取Cookies
from .访问网页 import 访问网页
from .输入文本 import 输入文本