from _typeshed import Incomplete

class InertiaApp:
    middlewares: Incomplete
    settings: Incomplete
    booted: bool
    def __init__(self) -> None: ...
    def boot(self) -> None: ...
    def get_djing_settings(self, django_settings, inertia_settings): ...
    def get_merged_settings(self, django_settings, djing_settings): ...
    def get_template_dirs(self) -> list: ...
    def get_static_dirs(self) -> list: ...
