from _typeshed import Incomplete as Incomplete

__version__: str
DOCKER_NS: str
REGISTRY_URL: str
on_linux: Incomplete

def color(s, color, mode: int = 1): ...
def red(s) -> None: ...
def green(s) -> None: ...
def yellow(s) -> None: ...
def error(msg, exit: bool = True) -> None: ...
def warn(msg) -> None: ...
def info(msg) -> None: ...
def in_repository() -> None: ...

IN_REPOSITORY: Incomplete

def fetch_registry(args, opener) -> None: ...

cache_validity: Incomplete
cache_dir: Incomplete
cache_file: Incomplete

def is_cache_valid(args) -> None: ...
def refresh_cache(args, force: bool = False) -> None: ...
def get_registry(args) -> None: ...
def make_name(reg, cfg, entry, solver) -> None: ...
def is_no_pattern(spec) -> None: ...

re_image_name: Incomplete

def valid_name(name) -> None: ...

class Repository:
    images: Incomplete
    names: Incomplete
    def __init__(self, args) -> None: ...

class ImageManager:
    repo: Incomplete
    name: Incomplete
    entry: Incomplete
    solver: Incomplete
    setup: Incomplete
    registry: Incomplete
    vars: Incomplete
    def __init__(self, name, repo) -> None: ...
    @property
    def solver_name(self) -> None: ...
    @property
    def status(self) -> None: ...

def get_list(args) -> None: ...
def print_list(args) -> None: ...
def print_info(args) -> None: ...
def check_cmd(argv) -> None: ...
def check_sudo() -> None: ...
def docker_call() -> None: ...
def check_docker() -> None: ...
def prepare_image(args, docker_argv, image) -> None: ...
def easy_volume(v) -> None: ...
def get_docker_volumes(args) -> None: ...
def docker_runs(args, images, docker_args=(), image_args=()) -> None: ...
def run_images(args) -> None: ...
def runraw_images(args) -> None: ...
def run_shell(args) -> None: ...
def extract(args) -> None: ...

FROM_UPTODATE: Incomplete

def docker_uptodate_image(args, docker_argv, image) -> None: ...
def docker_build(args, docker_argv, tag, root, build_args={}, Dockerfile: Incomplete | None = None) -> None: ...
def build_images(args) -> None: ...
def test_images(args) -> None: ...
def push_images(args) -> None: ...
def mrproper(args) -> None: ...
def dependencies(args) -> None: ...
def download_src(args) -> None: ...
def print_version(args) -> None: ...
def main(redirected: bool = False): ...
