# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .image_url_detail import ImageUrlDetail
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ImageUrl(UniversalBaseModel):
    url: typing.Optional[str] = None
    detail: typing.Optional[ImageUrlDetail] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
