# This file was auto-generated by Fern from our API Definition.

import typing
from .conversation_entry import ConversationEntry

VideoBotsPageOutputFinalPrompt = typing.Union[str, typing.List[ConversationEntry]]
