
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-13T08:36:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22a43b19a36622c11b96970eff2e8ab6776a7142",
 "version": "1.1.1.post0.dev90"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
