
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-16T13:59:58-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "65884c63c2f96185710d114a79c226b9a3184eca",
 "version": "4.1.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
