from enum import Enum


class SearchStep(Enum):
    PLANNED = "PLANNED"
    RETRIEVED = "RETRIEVED"
    FILE_SECTIONS_RETRIEVED = "FILE_SECTIONS_RETRIEVED"
    UNDOUBLED = "UNDOUBLED"
    RELEVANCE_GRADED = "RELEVANCE_GRADED"
    RELATED_DATA_GATHERED = "RELATED_DATA_GATHERED"
