# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.generic_error_response import GenericErrorResponse


class TooManyRequestsError(ApiError):
    def __init__(self, body: GenericErrorResponse):
        super().__init__(status_code=429, body=body)
