from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest

web: Incomplete

def signin(request: HttpRequest): ...
def index(request: HttpRequest): ...
def dashboard(request: HttpRequest, dashboard_name: str): ...
def resources(request, resource: str): ...
