
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-16T15:40:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bde1ca2b3fc505240868dcfe1553cd8f9e5708b0",
 "version": "0.3.0rc81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
