from _typeshed import Incomplete as Incomplete

class GeneralParser:
    info_parser: Incomplete
    parsed: Incomplete
    def __init__(self, info_parser, timestamp_types) -> None: ...
    def process_line(self, line, cpu_time_mili: Incomplete | None = None, wall_time_mili: Incomplete | None = None) -> None: ...

class TimeConverter:
    scale: int
    def __init__(self, time_scale) -> None: ...
    def convert(self, time) -> None: ...

def general_parser(path, parsing_info, timestamp: Incomplete | None = None, timestamp_types: Incomplete | None = None, time_scale: Incomplete | None = None): ...
