from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest

class Application:
    def __init__(self) -> None: ...
    @property
    def merged_config(self): ...
    @property
    def published(self): ...
    @property
    def publish_from_path(self): ...
    @property
    def publish_to_path(self): ...
    @property
    def working_directory(self): ...
    @property
    def base_prefix(self): ...
    @property
    def base_url(self): ...
    @property
    def user_model(self): ...
    @property
    def auth(self): ...
    request: Incomplete
    def set_base_url(self, request: HttpRequest) -> str: ...
    def run(self) -> None: ...
