from _typeshed import Incomplete
from optilog.formulas import CNF as CNF
from optilog.solvers.sat import Glucose41 as Glucose41

def propagate(formula, assumptions): ...

class PreProcessor:
    formula: Incomplete
    steps: Incomplete
    def __init__(self, formula) -> None: ...
    def add_call(self, fn, args, kwargs) -> None: ...
    @staticmethod
    def call_step(step, formula): ...
    def propagate(self, assumptions) -> None: ...
    def process(self): ...
