from _typeshed import Incomplete as Incomplete
from collections.abc import Generator

def opb_loader(input_data) -> Generator[Incomplete, None, None]: ...

class HeaderException(Exception): ...

class OPBParser:
    HEADER_LINE: Incomplete
    current_line: Incomplete
    comparator: str
    last_line: str
    def __init__(self, instance) -> None: ...
    def next(self) -> None: ...
    def current(self) -> None: ...
    def iterate(self) -> Generator[Incomplete, None, None]: ...
