# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetTablePrimaryIndex(BaseModel):
    table: Optional["GetTablePrimaryIndexTable"]


class GetTablePrimaryIndexTable(BaseModel):
    primary_index: List["GetTablePrimaryIndexTablePrimaryIndex"] = Field(
        alias="primaryIndex"
    )


class GetTablePrimaryIndexTablePrimaryIndex(BaseModel):
    name: str


GetTablePrimaryIndex.model_rebuild()
GetTablePrimaryIndexTable.model_rebuild()
