# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import List, Optional

from .base_model import BaseModel
from .enums import LevelType


class GetHierarchyLevels(BaseModel):
    cube: Optional["GetHierarchyLevelsCube"]


class GetHierarchyLevelsCube(BaseModel):
    dimension: Optional["GetHierarchyLevelsCubeDimension"]


class GetHierarchyLevelsCubeDimension(BaseModel):
    hierarchy: Optional["GetHierarchyLevelsCubeDimensionHierarchy"]
    name: str


class GetHierarchyLevelsCubeDimensionHierarchy(BaseModel):
    levels: List["GetHierarchyLevelsCubeDimensionHierarchyLevels"]
    name: str


class GetHierarchyLevelsCubeDimensionHierarchyLevels(BaseModel):
    name: str
    type: LevelType


GetHierarchyLevels.model_rebuild()
GetHierarchyLevelsCube.model_rebuild()
GetHierarchyLevelsCubeDimension.model_rebuild()
GetHierarchyLevelsCubeDimensionHierarchy.model_rebuild()
