# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateHierarchy(BaseModel):
    update_hierarchy: "UpdateHierarchyUpdateHierarchy" = Field(alias="updateHierarchy")


class UpdateHierarchyUpdateHierarchy(BaseModel):
    hierarchy: Optional["UpdateHierarchyUpdateHierarchyHierarchy"]


class UpdateHierarchyUpdateHierarchyHierarchy(BaseModel):
    are_members_indexed_by_name: bool = Field(alias="areMembersIndexedByName")


UpdateHierarchy.model_rebuild()
UpdateHierarchyUpdateHierarchy.model_rebuild()
