# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credential_proof_id import CredentialProofId
from .credential_proof_type import CredentialProofType


class CredentialProof(UniversalBaseModel):
    """
    A proof of a credential. [Terminology](https://www.w3.org/TR/vc-data-integrity/#proofs).
    """

    type: CredentialProofType
    id: typing.Optional[CredentialProofId] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
