# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic

from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .didcomm_message_field import DidcommMessageField
from .sort_order import SortOrder


class DidcommMessageSort(UniversalBaseModel):
    """
    Sort of the didcomm-messages' resources.
    """

    field: DidcommMessageField
    order: typing.Optional[SortOrder] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
