
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-12T15:34:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1ce570a80ef9bba353148d8075005bb462b93c4",
 "version": "2.45.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
