# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.models.any_of_match_entity_dossier_competition import AnyOfMatchEntityDossierCompetition  # noqa: E501
from apifff.rest import ApiException


class TestAnyOfMatchEntityDossierCompetition(unittest.TestCase):
    """AnyOfMatchEntityDossierCompetition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfMatchEntityDossierCompetition(self):
        """Test AnyOfMatchEntityDossierCompetition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apifff.models.any_of_match_entity_dossier_competition.AnyOfMatchEntityDossierCompetition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
