# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.models.any_of_calcul_match_histo_calcul_match_histo_match2 import AnyOfCalculMatchHistoCalculMatchHistoMatch2  # noqa: E501
from apifff.rest import ApiException


class TestAnyOfCalculMatchHistoCalculMatchHistoMatch2(unittest.TestCase):
    """AnyOfCalculMatchHistoCalculMatchHistoMatch2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfCalculMatchHistoCalculMatchHistoMatch2(self):
        """Test AnyOfCalculMatchHistoCalculMatchHistoMatch2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apifff.models.any_of_calcul_match_histo_calcul_match_histo_match2.AnyOfCalculMatchHistoCalculMatchHistoMatch2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
