class States:
    SCAFFOLDING: str = "SCAFFOLDING"
    INIT_STATE: str = "INIT_STATE"
    GEN_STATE: str = "GEN_STATE"
    SKILL_SELECTION: str = "SKILL_SELECTION"
    BEHAVIOUR_PLANNING: str = "BEHAVIOUR_PLANNING"
    BEHAVIOUR_GENERATION: str = "BEHAVIOUR_GENERATION"
