__version__ = '1.0.4'
__title__ = 'zwtk'
__description__ = 'Personal Python Utilities'
__url__ = 'https://github.com/njzhaowei/zwtk'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2024 Zhao Wei. All rights reserved.'
