import argparse

def none_parse_mem_units(size): ...
def none_parse_time_units(t): ...
def is_exe(fpath): ...
def exists(name): ...
def get_program(name, flag): ...
def path_or_err(string): ...

class ErrorHandlerParser(argparse.ArgumentParser):
    def __init__(self, *args, **kwargs) -> None: ...
    def error(self, message) -> None: ...

def parse_bool(val): ...
