from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest

class Application:
    def __init__(self) -> None: ...
    @property
    def initialized(self): ...
    @property
    def license_verifier(self): ...
    @property
    def license(self): ...
    @property
    def admin_root(self): ...
    @property
    def working_directory(self): ...
    @property
    def base_prefix(self): ...
    @property
    def base_url(self): ...
    @property
    def user_model(self): ...
    @property
    def auth(self): ...
    request: Incomplete
    def set_base_url(self, request: HttpRequest) -> str: ...
    def run(self) -> None: ...
