# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from apifff.api_client import ApiClient


class MatchMembreApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_match_membre_collection(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchMembre resources.  # noqa: E501

        Retrieves the collection of MatchMembre resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_membre_collection(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The collection page number
        :param int in_no:
        :param list[int] in_no:
        :param int match_entity_ma_no:
        :param list[int] match_entity_ma_no:
        :param int match_entity_sa_no:
        :param list[int] match_entity_sa_no:
        :param str po_cod:
        :param list[str] po_cod:
        :param int in_no_obs:
        :param list[int] in_no_obs:
        :param int cdg_cg_no:
        :param list[int] cdg_cg_no:
        :param int mm_no:
        :param list[int] mm_no:
        :param str order_match_entity_ma_dat:
        :param str match_entity_ma_dat_before:
        :param str match_entity_ma_dat_strictly_before:
        :param str match_entity_ma_dat_after:
        :param str match_entity_ma_dat_strictly_after:
        :return: InlineResponse20017
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_match_membre_collection_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_match_membre_collection_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_match_membre_collection_with_http_info(self, **kwargs):  # noqa: E501
        """Retrieves the collection of MatchMembre resources.  # noqa: E501

        Retrieves the collection of MatchMembre resources.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_match_membre_collection_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int page: The collection page number
        :param int in_no:
        :param list[int] in_no:
        :param int match_entity_ma_no:
        :param list[int] match_entity_ma_no:
        :param int match_entity_sa_no:
        :param list[int] match_entity_sa_no:
        :param str po_cod:
        :param list[str] po_cod:
        :param int in_no_obs:
        :param list[int] in_no_obs:
        :param int cdg_cg_no:
        :param list[int] cdg_cg_no:
        :param int mm_no:
        :param list[int] mm_no:
        :param str order_match_entity_ma_dat:
        :param str match_entity_ma_dat_before:
        :param str match_entity_ma_dat_strictly_before:
        :param str match_entity_ma_dat_after:
        :param str match_entity_ma_dat_strictly_after:
        :return: InlineResponse20017
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'in_no', 'in_no', 'match_entity_ma_no', 'match_entity_ma_no', 'match_entity_sa_no', 'match_entity_sa_no', 'po_cod', 'po_cod', 'in_no_obs', 'in_no_obs', 'cdg_cg_no', 'cdg_cg_no', 'mm_no', 'mm_no', 'order_match_entity_ma_dat', 'match_entity_ma_dat_before', 'match_entity_ma_dat_strictly_before', 'match_entity_ma_dat_after', 'match_entity_ma_dat_strictly_after']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_match_membre_collection" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'in_no' in params:
            query_params.append(('in_no', params['in_no']))  # noqa: E501
        if 'in_no' in params:
            query_params.append(('in_no[]', params['in_no']))  # noqa: E501
            collection_formats['in_no[]'] = 'multi'  # noqa: E501
        if 'match_entity_ma_no' in params:
            query_params.append(('match_entity.ma_no', params['match_entity_ma_no']))  # noqa: E501
        if 'match_entity_ma_no' in params:
            query_params.append(('match_entity.ma_no[]', params['match_entity_ma_no']))  # noqa: E501
            collection_formats['match_entity.ma_no[]'] = 'multi'  # noqa: E501
        if 'match_entity_sa_no' in params:
            query_params.append(('match_entity.sa_no', params['match_entity_sa_no']))  # noqa: E501
        if 'match_entity_sa_no' in params:
            query_params.append(('match_entity.sa_no[]', params['match_entity_sa_no']))  # noqa: E501
            collection_formats['match_entity.sa_no[]'] = 'multi'  # noqa: E501
        if 'po_cod' in params:
            query_params.append(('po_cod', params['po_cod']))  # noqa: E501
        if 'po_cod' in params:
            query_params.append(('po_cod[]', params['po_cod']))  # noqa: E501
            collection_formats['po_cod[]'] = 'multi'  # noqa: E501
        if 'in_no_obs' in params:
            query_params.append(('in_no_obs', params['in_no_obs']))  # noqa: E501
        if 'in_no_obs' in params:
            query_params.append(('in_no_obs[]', params['in_no_obs']))  # noqa: E501
            collection_formats['in_no_obs[]'] = 'multi'  # noqa: E501
        if 'cdg_cg_no' in params:
            query_params.append(('cdg.cg_no', params['cdg_cg_no']))  # noqa: E501
        if 'cdg_cg_no' in params:
            query_params.append(('cdg.cg_no[]', params['cdg_cg_no']))  # noqa: E501
            collection_formats['cdg.cg_no[]'] = 'multi'  # noqa: E501
        if 'mm_no' in params:
            query_params.append(('mm_no', params['mm_no']))  # noqa: E501
        if 'mm_no' in params:
            query_params.append(('mm_no[]', params['mm_no']))  # noqa: E501
            collection_formats['mm_no[]'] = 'multi'  # noqa: E501
        if 'order_match_entity_ma_dat' in params:
            query_params.append(('order[match_entity.ma_dat]', params['order_match_entity_ma_dat']))  # noqa: E501
        if 'match_entity_ma_dat_before' in params:
            query_params.append(('match_entity.ma_dat[before]', params['match_entity_ma_dat_before']))  # noqa: E501
        if 'match_entity_ma_dat_strictly_before' in params:
            query_params.append(('match_entity.ma_dat[strictly_before]', params['match_entity_ma_dat_strictly_before']))  # noqa: E501
        if 'match_entity_ma_dat_after' in params:
            query_params.append(('match_entity.ma_dat[after]', params['match_entity_ma_dat_after']))  # noqa: E501
        if 'match_entity_ma_dat_strictly_after' in params:
            query_params.append(('match_entity.ma_dat[strictly_after]', params['match_entity_ma_dat_strictly_after']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/ld+json', 'application/json', 'text/html'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/match_membres', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20017',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
