from _typeshed import Incomplete as Incomplete
from collections.abc import Generator
from optilog.tuning import Transformer as Transformer

class optilogEncoderTransformer(Transformer):
    card_enc: str
    def __init__(self, args) -> None: ...
    def run(self, cfg, seed, instance) -> None: ...
    pb_enc: Incomplete
    def lazy_run(self, cfg, seed, instance) -> Generator[Incomplete, Incomplete, None]: ...
    @staticmethod
    def get_params(args) -> None: ...
