# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_federated/proto/v0/data_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-tensorflow_federated/proto/v0/data_type.proto\x12\x17tensorflow_federated.v0*\xa6\x02\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0b\n\x07\x44T_BOOL\x10\n\x12\x0b\n\x07\x44T_INT8\x10\x06\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\x0c\n\x08\x44T_INT32\x10\x03\x12\x0c\n\x08\x44T_INT64\x10\t\x12\x0c\n\x08\x44T_UINT8\x10\x04\x12\r\n\tDT_UINT16\x10\x11\x12\r\n\tDT_UINT32\x10\x16\x12\r\n\tDT_UINT64\x10\x17\x12\x0b\n\x07\x44T_HALF\x10\x13\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\r\n\tDT_DOUBLE\x10\x02\x12\x10\n\x0c\x44T_COMPLEX64\x10\x08\x12\x11\n\rDT_COMPLEX128\x10\x12\x12\x0f\n\x0b\x44T_BFLOAT16\x10\x0e\x12\r\n\tDT_STRING\x10\x07\"\x04\x08\x0b\x10\x0b\"\x04\x08\x0c\x10\x0c\"\x04\x08\r\x10\r\"\x04\x08\x0f\x10\x0f\"\x04\x08\x10\x10\x10\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensorflow_federated.proto.v0.data_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=75
  _DATATYPE._serialized_end=369
# @@protoc_insertion_point(module_scope)
