from .Allinone import *
from .book import *
from .calculator import *
from .erfenchazhao_py import *
from .math_cal_py import *
from .student_py import *
from .tuxing_cal import *
from .xiaogongju import *
from lotterytickets import *
from numberandchinese import *