import torch

PITCH_MAX = 128
VELO = 128
LENGTH = 999
LENGTH_HALF = 999
BEGIN = 999
BEGIN_HALF = 999
ROOT = 99
START_SEQ_TOKEN = "<S_SEQ>"
END_SEQ_TOKEN = "<E_SEQ>"
PADDING_TOKEN = "<PAD>"

