# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.models.one_of_classement_journee_jsonld_context import OneOfClassementJourneeJsonldContext  # noqa: E501
from apifff.rest import ApiException


class TestOneOfClassementJourneeJsonldContext(unittest.TestCase):
    """OneOfClassementJourneeJsonldContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfClassementJourneeJsonldContext(self):
        """Test OneOfClassementJourneeJsonldContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apifff.models.one_of_classement_journee_jsonld_context.OneOfClassementJourneeJsonldContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
