# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.models.any_of_equipe_jsonld_equipe_club import AnyOfEquipeJsonldEquipeClub  # noqa: E501
from apifff.rest import ApiException


class TestAnyOfEquipeJsonldEquipeClub(unittest.TestCase):
    """AnyOfEquipeJsonldEquipeClub unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfEquipeJsonldEquipeClub(self):
        """Test AnyOfEquipeJsonldEquipeClub"""
        # FIXME: construct object with mandatory attributes with example values
        # model = apifff.models.any_of_equipe_jsonld_equipe_club.AnyOfEquipeJsonldEquipeClub()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
