from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest
from django.urls import get_resolver as get_resolver

class Application:
    resource_classes: Incomplete
    resource_instances: Incomplete
    djing_urls: Incomplete
    def __init__(self) -> None: ...
    @property
    def config(self): ...
    @property
    def is_published(self): ...
    @property
    def publish_from_path(self): ...
    @property
    def publish_to_path(self): ...
    @property
    def working_directory(self): ...
    request: Incomplete
    def set_request(self, request: HttpRequest) -> str: ...
    def run(self) -> None: ...
