from _typeshed import Incomplete
from django.http import HttpRequest as HttpRequest
from djing.core.base_config import BaseConfig
from djing.core.base_provider import BaseProvider
from typing import Self

class Application:
    publish_to_dir_name: str
    resource_classes: Incomplete
    resource_instances: Incomplete
    djing_urls: Incomplete
    def __init__(self) -> None: ...
    @property
    def provider(self) -> BaseProvider: ...
    @property
    def config(self) -> BaseConfig: ...
    @property
    def publish_from_path(self): ...
    @property
    def publish_to_path(self): ...
    @property
    def working_directory(self): ...
    @property
    def user_model(self): ...
    @property
    def auth(self): ...
    @property
    def base_url(self) -> str: ...
    request: Incomplete
    def set_request(self, request: HttpRequest) -> str: ...
    def boot(self) -> Self: ...
    def run(self) -> None: ...
    def is_published(self): ...
