# This file was auto-generated by Fern from our API Definition.

import typing

ControlNetModels = typing.Union[
    typing.Literal[
        "sd_controlnet_canny",
        "sd_controlnet_depth",
        "sd_controlnet_hed",
        "sd_controlnet_mlsd",
        "sd_controlnet_normal",
        "sd_controlnet_openpose",
        "sd_controlnet_scribble",
        "sd_controlnet_seg",
        "sd_controlnet_tile",
        "sd_controlnet_brightness",
        "control_v1p_sd15_qrcode_monster_v2",
    ],
    typing.Any,
]
