import argparse

def none_parse_mem_units(size) -> None: ...
def none_parse_time_units(t) -> None: ...
def is_exe(fpath) -> None: ...
def exists(name) -> None: ...
def get_program(name, flag) -> None: ...
def path_or_err(string) -> None: ...

class ErrorHandlerParser(argparse.ArgumentParser):
    def __init__(self, *args, **kwargs) -> None: ...
    def error(self, message) -> None: ...

def parse_bool(val) -> None: ...
