from .configurator_wrapper import set_wrapper_subparser as set_wrapper_subparser
from _typeshed import Incomplete
from optilog.blackbox import BlackBox as BlackBox
from optilog.internalutils import parse_bool as parse_bool
from optilog.tuning import config_str_to_dict as config_str_to_dict
from optilog.tuning.configurators.abstract_configurator import AbstractConfigurator as AbstractConfigurator

def tuning_execution(configurator, context) -> None: ...
def set_execution_subparser(parent) -> None: ...

class TuningEntrypoint:
    configurator: Incomplete
    args: Incomplete
    params: Incomplete
    input_type: Incomplete
    cwd: Incomplete
    def __init__(self, configurator: AbstractConfigurator, args, params) -> None: ...
    def parse_args(self): ...
    def get_instance(self): ...
    def prepare_kwargs(self): ...
    def prepare_entrypoint(self): ...
    def main(self) -> None: ...

def main(configurator: AbstractConfigurator, args, params): ...
