# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataidea-science',
                'doc_host': 'https://dataideaorg.github.io',
                'git_url': 'https://github.com/dataideaorg/dataidea-science',
                'lib_path': 'dataidea_science'},
  'syms': { 'dataidea_science.core': {'dataidea_science.core.foo': ('core.html#foo', 'dataidea_science/core.py')},
            'dataidea_science.datasets': {},
            'dataidea_science.plots': {}}}
