from _typeshed import Incomplete as Incomplete
from optilog.tuning.configurators.abstract_configurator import AbstractConfigurator as AbstractConfigurator

def tuning_execution(configurator, context) -> None: ...
def set_execution_subparser(parent) -> None: ...

class TuningEntrypoint:
    configurator: Incomplete
    args: Incomplete
    params: Incomplete
    input_type: Incomplete
    cwd: Incomplete
    def __init__(self, configurator: AbstractConfigurator, args, params) -> None: ...
    def parse_args(self) -> None: ...
    def get_instance(self) -> None: ...
    def prepare_kwargs(self) -> None: ...
    def prepare_entrypoint(self) -> None: ...
    def main(self) -> None: ...

def main(configurator: AbstractConfigurator, args, params): ...
