# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.api.calcul_match_histo_api import CalculMatchHistoApi  # noqa: E501
from apifff.rest import ApiException


class TestCalculMatchHistoApi(unittest.TestCase):
    """CalculMatchHistoApi unit test stubs"""

    def setUp(self):
        self.api = CalculMatchHistoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_calcul_match_histo_collection(self):
        """Test case for get_calcul_match_histo_collection

        Retrieves the collection of CalculMatchHisto resources.  # noqa: E501
        """
        pass

    def test_get_calcul_match_histo_item(self):
        """Test case for get_calcul_match_histo_item

        Retrieves a CalculMatchHisto resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
