# coding: utf-8

"""

    # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    OpenAPI spec version: 0.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import apifff
from apifff.api.arbitre_api import ArbitreApi  # noqa: E501
from apifff.rest import ApiException


class TestArbitreApi(unittest.TestCase):
    """ArbitreApi unit test stubs"""

    def setUp(self):
        self.api = ArbitreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_arbitre_collection(self):
        """Test case for get_arbitre_collection

        Retrieves the collection of Arbitre resources.  # noqa: E501
        """
        pass

    def test_get_arbitre_item(self):
        """Test case for get_arbitre_item

        Retrieves a Arbitre resource.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
