import numpy as np

class DataFrameF64:
    index: np.ndarray
    columns: np.ndarray
    data: np.ndarray

INDEX_CHAR_LEN: int

def new(index: np.ndarray, columns: np.ndarray, data: np.ndarray) -> DataFrameF64: ...
def shape(df: DataFrameF64) -> tuple[int, int]: ...
def rows(df: DataFrameF64, indices: np.ndarray) -> DataFrameF64: ...
def index(df: DataFrameF64) -> np.ndarray: ...
def columns(df: DataFrameF64) -> np.ndarray: ...
def values(df: DataFrameF64) -> np.ndarray: ...
