
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-18T00:09:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d240bc5230efb8529c68ee14d25c06c1bc4a69c",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
